### ISSUE TITLE
package.json `exports` has `default` before `types` — breaks TypeScript module resolution

### ISSUE THREAD

**Issue by buildmaster** [unlight/prisma-graphql-type-decimal#13]
## Problem

`prisma-graphql-type-decimal@4.0.3` (and current `master`) declares:

```json
"exports": {
  ".": {
    "default": "./prisma-graphql-type-decimal.mjs",
    "types": "./prisma-graphql-type-decimal.d.ts"
  }
}
```

Conditional exports are matched **in declaration order**, and the `types` condition must come **first** (before `default`/`import`/`require`) or TypeScript cannot resolve type declarations through the exports map.

With the current ordering, any TypeScript project that imports `GraphQLDecimal` or `transformToDecimal` fails with:

```
error TS2307: Cannot find module 'prisma-graphql-type-decimal' or its corresponding type declarations.
```

This happens under `moduleResolution: "node16" | "nodenext" | "bundler"` (i.e. everyone on a modern setup). It worked in 4.0.2 only because 4.0.2 had no `types` key inside `exports` and TypeScript fell back to the top-level `types` field.

## Reproduction

In a fresh TypeScript project with `"moduleResolution": "bundler"` (or `node16`):

```bash
npm i prisma-graphql-type-decimal@4.0.3
echo "import { GraphQLDecimal } from 'prisma-graphql-type-decimal'; console.log(GraphQLDecimal);" > x.ts
npx tsc --noEmit x.ts
# → error TS2307: Cannot find module 'prisma-graphql-type-decimal' or its corresponding type declarations.
```

Downgrading to 4.0.2 resolves it (no `types` inside `exports`, falls back to top-level `types`).

## Fix

Swap the order so `types` comes first:

```json
"exports": {
  ".": {
    "types": "./prisma-graphql-type-decimal.d.ts",
    "default": "./prisma-graphql-type-decimal.mjs"
  }
}
```

## References

- TypeScript handbook — *Publishing › "exports" condition*: https://www.typescriptlang.org/docs/handbook/modules/reference.html#packagejson-exports-imports-and-self-referencing — explicitly: *"The `types` condition should always come first in `exports`."*
- TS 4.7 release notes (when this rule was introduced): https://devblogs.microsoft.com/typescript/announcing-typescript-4-7/#package-json-exports-imports-and-self-referencing — *"It's important to note that the `types` condition should always come first in `"exports"`."*
- Node.js conditional-exports docs (order-sensitive matching): https://nodejs.org/api/packages.html#conditional-exports
- `@arethetypeswrong/cli` flags this exact issue as `FalseExportDefault` / types-not-resolved.

## Context

Spotted while bumping deps in a downstream project; the API build broke across every generated input that imports `GraphQLDecimal`. Pinning back to 4.0.2 in the meantime. Happy to send a PR if useful.
